persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Izinkan koneksi tanpa password untuk lokal development
listener 1883
allow_anonymous true

# Listener untuk WebSockets (Opsional, berguna untuk dashboard web masa depan)
listener 9001
protocol websockets
allow_anonymous true
